# Generated by Django 3.1.2 on 2021-12-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_usermodel_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
    ]
