name: Semgrep

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '33 1 * * 0'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      # Checkout project source
      - uses: actions/checkout@v3

      # Scan code using project's configuration on https://semgrep.dev/manage
      # Run the "semgrep ci" command on the command line of the docker image.
      
        with:
          config: p/r2c-ci
          generateSarif: "1"
          auditOn: push
      - run: semgrep --config "p/default" && semgrep ci --sarif --output=semgrep.sarif
#       - uses: returntocorp/semgrep@v2

      # Upload SARIF file generated in previous step
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: hashFiles('semgrep.sarif') != ''
